- name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN... }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### ESTAS SON LAS LÍNEAS CLAVE ######
          app_location: "/"       # Dónde está tu index.html
          api_location: ""        # Vacío
          output_location: "."    # Un punto (significa "aquí mismo")
          skip_app_build: true    # <--- ESTO EVITA EL ERROR DE NPM
          ########################################