- name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN... }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### CONFIGURACIÓN HTML PURO ######
          app_location: "/"      # Raíz de tus archivos
          api_location: ""       # Déjalo vacío
          output_location: "."   # IMPORTANTE: Un punto (o vacío) significa "aquí mismo"
          #####################################